# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llk_h2_rho <- function(rho, h2_1, h2_2, sigma_1, sigma_2, n_1, n_2, num_SNP, z_1, z_2, R_1, R_2) {
    .Call(`_Logica_llk_h2_rho`, rho, h2_1, h2_2, sigma_1, sigma_2, n_1, n_2, num_SNP, z_1, z_2, R_1, R_2)
}

llk_h2_est <- function(h2, sigma, z, R, n, num_SNP) {
    .Call(`_Logica_llk_h2_est`, h2, sigma, z, R, n, num_SNP)
}

llk_sigma_e_est <- function(sigma, z, R, n, num_SNP) {
    .Call(`_Logica_llk_sigma_e_est`, sigma, z, R, n, num_SNP)
}

llk_h2_trans_est <- function(h2, sigma, Utz, eig_val, n, num_SNP) {
    .Call(`_Logica_llk_h2_trans_est`, h2, sigma, Utz, eig_val, n, num_SNP)
}

llk_sigma_e_trans_est <- function(sigma, Utz, eig_val) {
    .Call(`_Logica_llk_sigma_e_trans_est`, sigma, Utz, eig_val)
}

est_h2_null_score <- function(h2_1, h2_2, sigma_1, sigma_2, z_1, z_2, R_1, R_2, n_1, n_2, num_SNP, max_iter = 100L, fix_intercept = FALSE) {
    .Call(`_Logica_est_h2_null_score`, h2_1, h2_2, sigma_1, sigma_2, z_1, z_2, R_1, R_2, n_1, n_2, num_SNP, max_iter, fix_intercept)
}

PX_EM_alt <- function(h2_1, h2_2, rho, sigma_1, sigma_2, z_1, z_2, R_1, R_2, n_1, n_2, num_SNP, n_iter = 1000L, fix_intercept = FALSE, fix_h2 = FALSE) {
    .Call(`_Logica_PX_EM_alt`, h2_1, h2_2, rho, sigma_1, sigma_2, z_1, z_2, R_1, R_2, n_1, n_2, num_SNP, n_iter, fix_intercept, fix_h2)
}

